default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
development:
  <<: *default
  database: fair_project_dev_db
test:
  <<: *default
  database: fair_project_test_db
production:
  <<: *default
  database: fair_project_prod_db